name:                bitcoin-price
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/bitcoin-price#readme
license:             BSD3
author:              Jonathan Healy
maintainer:          jonathan.d.healy@gmail.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - lens
  - lens-aeson
  - bytestring
  - text
  - http-conduit

executables:
  bitcoin-price:
    source-dirs:      src
    main:             Main.hs
